version: "3.9"

services:
  backend:
    build: .
    container_name: uber-backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/uber_clone
      - PORT=4000
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: uber-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=uber_clone
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
